CATodo.WebApp/Controllers/TodoController.cs
using CATodo.BLLContracts;
using CATodo.WebApp.Models.Extensions;
using CATodo.WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CATodo.WebApp.Controllers {
    public class TodoController : Controller {
        public ICATodoService TodoService { get; }
        public TodoController(ICATodoService todoService) {
            TodoService = todoService;
        }

        public IActionResult Index([FromQuery] string? categoryId) {
            var categories = TodoService.ListAllCategories().OrderBy(c => c.Name).Select(c => c.ToCategoryModel());

            int? catId = null;
            if (int.TryParse(categoryId, out int id)) { catId = id; }
            var data = catId.HasValue ? TodoService.ListTodosByCategory(catId.Value) : TodoService.ListAllTodos();
            var todos = data.OrderBy(t => t.Title).Select(
                t => t.ToTodoModel(categories.First(c => c.Id == t.CategoryId))
            ).ToList();

            var categoryListItems = new List<SelectListItem>() { new SelectListItem() { Text = "Toutes", Value = "" } };
            categoryListItems.AddRange(
                categories.Select(c => new SelectListItem() {
                    Text = c.Name,
                    Value = c.Id.ToString(),
                    Selected = c.Id == catId
                })
            );
            var vm = new TodoIndexViewModel() {
                Categories = categories.ToList(),
                Todos = todos.ToList(),
                CategoryListItems = categoryListItems
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Delete([FromQuery] string? categoryId) {
            TodoService.RemoveTodo(int.Parse(HttpContext.Request.Form["todoId"].ToString()));
            return RedirectToAction("Index", new { categoryId = categoryId });
        }

        [HttpPost]
        public IActionResult Toggle([FromQuery] string? categoryId) {
            TodoService.ToggleTodo(int.Parse(HttpContext.Request.Form["todoId"].ToString()));
            return RedirectToAction("Index", new { categoryId = categoryId });
        }

        [HttpGet]
        public IActionResult Create() {
            var vm = new TodoCreateViewModel() {
                DueDate = DateTime.Today,
                Categories = GenerateCategoryListItems()
            };
            return View(vm);
        }

        private List<SelectListItem> GenerateCategoryListItems() {
            var categories = TodoService.ListAllCategories().OrderBy(c => c.Name).Select(c => c.ToCategoryModel());
            var categoryListItems = new List<SelectListItem>() {
                new SelectListItem() { Text = "Choisissez une catégorie", Value = "" }
            };
            categoryListItems.AddRange(
                categories.Select(c => new SelectListItem() {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
            );
            return categoryListItems;
        }

        [HttpPost]
        public IActionResult Create(TodoCreateViewModel vm) {
            if (ModelState.IsValid) {
                try {
                    TodoService.CreateTodo(new TodoCreate() {
                        CategoryId = vm.CategoryId,
                        Description = vm.Description,
                        DueDate = vm.DueDate,
                        Latitude = vm.Latitude,
                        Longitude = vm.Longitude,
                        Title = vm.Title
                    });
                    return RedirectToAction("Index");
                } catch (CATodoException ex) {
                    ex.Message
                        .Split(";")
                        .ToList()
                        .ForEach(m => ModelState.AddModelError("", m));
                }
            }
            vm.Categories = GenerateCategoryListItems();
            return View(vm);
        }
    }
}

CATodo.WebApp/Views/Todo/Create.cshtml
@model CATodo.WebApp.ViewModels.TodoCreateViewModel

@{
    ViewData["Title"] = "Create";
}
<div>
    <a asp-action="Index">retour</a>
</div>
<h4>Mon nouveau truc à faire</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                @*<input asp-for="CategoryId" class="form-control" />*@
                <select asp-for="CategoryId" asp-items="@Model.Categories" class="form-select"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude"  data-val-number="pas bien !" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" type="number" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Ajouter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">retour</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CATodo.WebApp/Views/Todo/Index.cshtml
@model CATodo.WebApp.ViewModels.TodoIndexViewModel
@{
    ViewData["Title"] = "Mes trucs à faire";
}
<div>
    <a asp-controller="Todo" asp-action="Create" class="float-end">
        <i class="fa fa-plus-circle fa-3x text-primary"></i>
    </a>

    <h4><i class="fa fa-clipboard-list"></i> Mes trucs à faire</h4>

    <form method="get">
        <label>Filtrer par catégorie</label>
        <select name="categoryId" class="form-select" asp-items="Model.CategoryListItems"></select>
        <button class="btn btn-primary">Filtrer</button>
    </form>

    <hr />
</div>

@foreach (var todo in Model.Todos) {
    <div class="card mb-2">
        <div class="card-header">
            <form class="float-end"
                  asp-action="Toggle"
                  asp-route-categoryId="@Model.CategoryListItems.FirstOrDefault(c => c.Selected)?.Value">
                <input type="hidden" name="todoId" value="@todo.Id" />
                <button class="btn btn-link" style="color:inherit">
                    <i class="far fa@(todo.IsDone?"-check":"")-circle fa-3x float-end"></i>
                </button>
            </form>

            <span class="badge text-dark" style="background-color: @todo.Category.Color">
                @Html.DisplayFor(m => todo.Category.Name)
            </span>
            <h4>@Html.DisplayFor(m => todo.Title)</h4>
        </div>
        <div class="card-body">
            <span class="badge bg-dark float-end ms-2">
                @Html.DisplayFor(m => todo.DueDate)
            </span>
            <p>@Html.DisplayFor(m => todo.Description)</p>

            @if (todo.IsLocation) {
                <a href="@todo.MapUrl" target="_blank" class="btn btn-light">
                    <i class="fa fa-map-marked-alt"></i>
                    voir sur la carte (@Html.DisplayFor(m => todo.Location))
                </a>
            }
        </div>
        <div class="card-footer">
            @if (todo.IsRemovable) {
                <form asp-action="Delete"
                      asp-route-categoryId="@Model.CategoryListItems.FirstOrDefault(c => c.Selected)?.Value">
                    <input type="hidden" name="todoId" value="@todo.Id" />
                    <button class="btn btn-danger float-end">
                        <i class="fa fa-trash-alt"></i>
                    </button>
                </form>
            }

            @{
                var severity = todo.Status switch {
                    TodoStatus.Archived or TodoStatus.Closed => "secondary",
                    TodoStatus.Pending => "success",
                    TodoStatus.Late => "warning"
                };
            }
            <span class="badge bg-@severity">
                @Html.DisplayFor(m => todo.StatusText)
            </span>
        </div>
    </div>
}